// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbYDuLLf4yAQm731s0CF_3THlm280FV50',
    appId: '1:335055918040:web:2a8f2154cda9bea835d8ad',
    messagingSenderId: '335055918040',
    projectId: 'expense-tracker-53ee9',
    authDomain: 'expense-tracker-53ee9.firebaseapp.com',
    storageBucket: 'expense-tracker-53ee9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB74x_78CsfRfxhMBm7BItq5O-VQ1ec4YU',
    appId: '1:335055918040:android:77c91e99b57e496135d8ad',
    messagingSenderId: '335055918040',
    projectId: 'expense-tracker-53ee9',
    storageBucket: 'expense-tracker-53ee9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM8vkA3LEgPdO0KDFiF051Rb7N7lflg9I',
    appId: '1:335055918040:ios:0839f869a896783d35d8ad',
    messagingSenderId: '335055918040',
    projectId: 'expense-tracker-53ee9',
    storageBucket: 'expense-tracker-53ee9.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM8vkA3LEgPdO0KDFiF051Rb7N7lflg9I',
    appId: '1:335055918040:ios:0839f869a896783d35d8ad',
    messagingSenderId: '335055918040',
    projectId: 'expense-tracker-53ee9',
    storageBucket: 'expense-tracker-53ee9.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbYDuLLf4yAQm731s0CF_3THlm280FV50',
    appId: '1:335055918040:web:39b1d3f21c87469335d8ad',
    messagingSenderId: '335055918040',
    projectId: 'expense-tracker-53ee9',
    authDomain: 'expense-tracker-53ee9.firebaseapp.com',
    storageBucket: 'expense-tracker-53ee9.firebasestorage.app',
  );
}
